### PR TITLE
Config with pure python

### PR DESCRIPTION
**Pull request by icemac**
* Lint the code.
* Drop support for Python 3.4.
* Add support for Python 3.8, 3.9, 3.10.

### CODE REVIEW

**Review by dataflake — CHANGES_REQUESTED** [review]
`setup.py` is missing `python_requires`?

**Comment by icemac** [comment]
@dataflake Thank you for your review. I copied over `python_requires` from `zope.interface`. Is it okay now?

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
Yes it is OK. This was the first time I actively looked for `python_requires`, I wonder if there are other packages that have been updated but miss it.

By the way, I'd prefer the simple string form, not a programming statement that creates one. I'd consider that overly complicated.

**Comment by icemac** [comment]
Other ones miss `python_requires`, too. At least the drop-Python-2-guide mentions adding it. So we'll probably get it by then.

Thank you for reviewing this PR. 😃

**Pull request merged**
